
// List of Swedish Wildlife (Viltboken)
window.swedishAnimals = [
    {
        "id": "moose",
        "type": "Hovdjur",
        "nameEn": "Moose",
        "nameSv": "Älg",
        "scientific": "Alces alces",
        "rarity": 1,
        "funFact": "Älgen kallas 'Skogens Konung' och är världens största hjortdjur. Sverige har omkring 300 000 älgar.",
        "seasonDistribution": "Hela landet",
        "height": 200, // cm (shoulder height)
        "weight": 400000, // g (400kg)
        "bestTime": "Gryning/Skymning"
    },
    {
        "id": "red_fox",
        "type": "Rovdjur",
        "nameEn": "Red Fox",
        "nameSv": "Rödräv",
        "scientific": "Vulpes vulpes",
        "rarity": 1,
        "funFact": "Räven kan höra en sork röra sig under 30 cm snö på 100 meters avstånd.",
        "seasonDistribution": "Hela landet",
        "height": 40,
        "weight": 7000,
        "bestTime": "Natt/Gryning"
    },
    {
        "id": "roe_deer",
        "type": "Hovdjur",
        "nameEn": "Roe Deer",
        "nameSv": "Rådjur",
        "scientific": "Capreolus capreolus",
        "rarity": 1,
        "funFact": "Rådjuret skäller som en hund när det blir skrämt och bocken markerar revir med hornmassage på träd.",
        "seasonDistribution": "Södra/Mellersta Sverige",
        "height": 70,
        "weight": 25000,
        "bestTime": "Gryning/Skymning"
    },
    {
        "id": "brown_bear",
        "type": "Rovdjur",
        "nameEn": "Brown Bear",
        "nameSv": "Brunbjörn",
        "scientific": "Ursus arctos",
        "rarity": 3,
        "funFact": "Under vinterdvalan sjunker björnens hjärtfrekvens från 40 till 8 slag per minut.",
        "seasonDistribution": "Norra/Mellersta Sverige",
        "height": 100, // shoulder
        "weight": 200000,
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "european_hedgehog",
        "type": "Insektsätare",
        "nameEn": "European Hedgehog",
        "nameSv": "Igelkott",
        "scientific": "Erinaceus europaeus",
        "rarity": 2,
        "funFact": "Igelkotten har cirka 5000–7000 taggar och kan simma och klättra överraskande bra.",
        "seasonDistribution": "Södra/Mellersta Sverige",
        "height": 15,
        "weight": 1000,
        "bestTime": "Natt"
    },
    {
        "id": "wolf",
        "type": "Rovdjur",
        "nameEn": "Grey Wolf",
        "nameSv": "Varg",
        "scientific": "Canis lupus",
        "rarity": 4,
        "funFact": "Vargen återetablerade sig naturligt i Sverige på 1980-talet. Idag finns 300–400 individer.",
        "seasonDistribution": "Mellersta Sverige",
        "height": 80,
        "weight": 40000,
        "bestTime": "Natt/Gryning"
    },
    {
        "id": "lynx",
        "type": "Rovdjur",
        "nameEn": "Eurasian Lynx",
        "nameSv": "Lo",
        "scientific": "Lynx lynx",
        "rarity": 3,
        "funFact": "Lodjuret är den enda stora katten i Norden och kan ta byten dubbelt så stora som sig självt.",
        "seasonDistribution": "Hela landet",
        "height": 70,
        "weight": 25000,
        "bestTime": "Natt"
    },
    {
        "id": "wolverine",
        "type": "Rovdjur",
        "nameEn": "Wolverine",
        "nameSv": "Järv",
        "scientific": "Gulo gulo",
        "rarity": 4,
        "funFact": "Järven är känd för sin otroliga styrka – den kan dra ett annat djur tre gånger sin egen vikt.",
        "seasonDistribution": "Norra Sverige",
        "height": 45,
        "weight": 15000,
        "bestTime": "Natt/Dag"
    },
    {
        "id": "red_deer",
        "type": "Hovdjur",
        "nameEn": "Red Deer",
        "nameSv": "Kronhjort",
        "scientific": "Cervus elaphus",
        "rarity": 2,
        "funFact": "Kronhjortens brunstskrik (rötet) kan höras på kilometers avstånd under september månad.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 140,
        "weight": 150000,
        "bestTime": "Gryning/Skymning"
    },
    {
        "id": "fallow_deer",
        "type": "Hovdjur",
        "nameEn": "Fallow Deer",
        "nameSv": "Dovhjort",
        "scientific": "Dama dama",
        "rarity": 2,
        "funFact": "Dovhjortens palmade (flattade) horn är karakteristiska. Ursprungligen från Medelhavsområdet.",
        "seasonDistribution": "Södra Sverige",
        "height": 95,
        "weight": 60000,
        "bestTime": "Gryning/Skymning"
    },
    {
        "id": "wild_boar",
        "type": "Hovdjur",
        "nameEn": "Wild Boar",
        "nameSv": "Vildsvin",
        "scientific": "Sus scrofa",
        "rarity": 2,
        "funFact": "Vildsvinet etablerade sig i Sverige på 1970-talet och räknas nu till hundratusentals.",
        "seasonDistribution": "Södra och Mellersta Sverige",
        "height": 80,
        "weight": 100000,
        "bestTime": "Natt/Gryning"
    },
    {
        "id": "eurasian_beaver",
        "type": "Gnagare",
        "nameEn": "Eurasian Beaver",
        "nameSv": "Europeisk bäver",
        "scientific": "Castor fiber",
        "rarity": 2,
        "funFact": "Bävern utrottades i Sverige men återinfördes på 1920-talet och lever nu i hela landet.",
        "seasonDistribution": "Hela landet",
        "height": 40,
        "weight": 20000,
        "bestTime": "Kväll/Natt"
    },
    {
        "id": "european_badger",
        "type": "Mårddjur",
        "nameEn": "European Badger",
        "nameSv": "Grävling",
        "scientific": "Meles meles",
        "rarity": 2,
        "funFact": "Grävlingen är ett av få djur i världen som kan äta igelkottar – den bara rullar ihop dem.",
        "seasonDistribution": "Hela landet",
        "height": 30,
        "weight": 12000,
        "bestTime": "Natt"
    },
    {
        "id": "eurasian_otter",
        "type": "Mårddjur",
        "nameEn": "Eurasian Otter",
        "nameSv": "Utter",
        "scientific": "Lutra lutra",
        "rarity": 3,
        "funFact": "Uttern kan hålla andan i upp till 8 minuter och simma med en fart av 12 km/h.",
        "seasonDistribution": "Hela landet",
        "height": 30,
        "weight": 10000,
        "bestTime": "Natt/Gryning"
    },
    {
        "id": "pine_marten",
        "type": "Mårddjur",
        "nameEn": "Pine Marten",
        "nameSv": "Skogsmård",
        "scientific": "Martes martes",
        "rarity": 2,
        "funFact": "Skogsmården är ett av de snabbaste djuren i skogen och kan hoppa 4 meter mellan träd.",
        "seasonDistribution": "Hela landet",
        "height": 15,
        "weight": 1500,
        "bestTime": "Natt"
    },
    {
        "id": "stoat",
        "type": "Mårddjur",
        "nameEn": "Stoat / Ermine",
        "nameSv": "Hermelin",
        "scientific": "Mustela erminea",
        "rarity": 2,
        "funFact": "På vintern byter hermelinen päls till vit med svart svanstipp – den vita pälsen kallas hermelin.",
        "seasonDistribution": "Hela landet",
        "height": 10,
        "weight": 200,
        "bestTime": "Dag/Natt"
    },
    {
        "id": "least_weasel",
        "type": "Mårddjur",
        "nameEn": "Least Weasel",
        "nameSv": "Vessla",
        "scientific": "Mustela nivalis",
        "rarity": 2,
        "funFact": "Vesslan är världens minsta rovdjur men kan ta byten 10 gånger sin egen storlek.",
        "seasonDistribution": "Hela landet",
        "height": 6,
        "weight": 60,
        "bestTime": "Dag/Natt"
    },
    {
        "id": "mountain_hare",
        "type": "Harar",
        "nameEn": "Mountain Hare",
        "nameSv": "Skogshare",
        "scientific": "Lepus timidus",
        "rarity": 1,
        "funFact": "Skogsharen byter päls till vit inför vintern och är ett byte för nästan alla svenska rovdjur.",
        "seasonDistribution": "Hela landet",
        "height": 30,
        "weight": 3500,
        "bestTime": "Natt/Gryning"
    },
    {
        "id": "european_rabbit",
        "type": "Harar",
        "nameEn": "European Rabbit",
        "nameSv": "Vildkanin",
        "scientific": "Oryctolagus cuniculus",
        "rarity": 2,
        "funFact": "Vildkaninen lever i jordhålor (kolonier) och är ursprungligen importerad till Sverige.",
        "seasonDistribution": "Södra Sverige (kusten)",
        "height": 20,
        "weight": 2000,
        "bestTime": "Gryning/Kväll"
    },
    {
        "id": "common_squirrel",
        "type": "Gnagare",
        "nameEn": "Red Squirrel",
        "nameSv": "Ekorre",
        "scientific": "Sciurus vulgaris",
        "rarity": 1,
        "funFact": "Ekorren gömmer tusentals nötter varje höst och hittar dem igen med hjälp av minne och luktsinne.",
        "seasonDistribution": "Hela landet",
        "height": 10,
        "weight": 300,
        "bestTime": "Dag"
    },
    {
        "id": "bank_vole",
        "type": "Gnagare",
        "nameEn": "Bank Vole",
        "nameSv": "Skogssork",
        "scientific": "Myodes glareolus",
        "rarity": 1,
        "funFact": "Skogssorken har kraftiga populationscykler var 3–4 år (lemingelår) som påverkar hela ekosystemet.",
        "seasonDistribution": "Hela landet",
        "height": 5,
        "weight": 20,
        "bestTime": "Dag/Natt"
    },
    {
        "id": "common_shrew",
        "type": "Insektsätare",
        "nameEn": "Common Shrew",
        "nameSv": "Näbbmus",
        "scientific": "Sorex araneus",
        "rarity": 1,
        "funFact": "Näbbmusen måste äta var 2–3 timme dygnet runt annars svälter den ihjäl – ett av de högsta ämnesomsättning bland däggdjur.",
        "seasonDistribution": "Hela landet",
        "height": 4,
        "weight": 12,
        "bestTime": "Dag/Natt"
    },
    {
        "id": "reindeer",
        "type": "Hovdjur",
        "nameEn": "Reindeer",
        "nameSv": "Ren",
        "scientific": "Rangifer tarandus",
        "rarity": 2,
        "funFact": "Renen är det enda hjortdjuret där även honorna bär horn. I fjällen lever ca 250 000 tamrenar.",
        "seasonDistribution": "Norra Sverige (Lappland)",
        "height": 120,
        "weight": 100000,
        "bestTime": "Dag"
    },
    {
        "id": "mink",
        "type": "Mårddjur",
        "nameEn": "American Mink",
        "nameSv": "Mink",
        "scientific": "Neovison vison",
        "rarity": 2,
        "funFact": "Minken är ett invasivt djur som rymt från pälsfarmer och nu koloniserat hela Sverige.",
        "seasonDistribution": "Hela landet",
        "height": 15,
        "weight": 1000,
        "bestTime": "Natt/Gryning"
    },
    {
        "id": "common_seal",
        "type": "Sälar",
        "nameEn": "Harbour Seal",
        "nameSv": "Knubbsäl",
        "scientific": "Phoca vitulina",
        "rarity": 2,
        "funFact": "Knubbsälen är Sveriges vanligaste säl och vilar gärna på klippor och sandbankar längs kusten.",
        "seasonDistribution": "Västerhavet & Östersjön (kuster)",
        "height": 80,
        "weight": 75000,
        "bestTime": "Dag"
    },
    {
        "id": "ringed_seal",
        "type": "Sälar",
        "nameEn": "Ringed Seal",
        "nameSv": "Vikare",
        "scientific": "Pusa hispida",
        "rarity": 3,
        "funFact": "Vikaren lever i Östersjön och Bottenhavet och är en av isbjörnens viktigaste bytesdjur i Arktis.",
        "seasonDistribution": "Östersjön (norra)",
        "height": 70,
        "weight": 50000,
        "bestTime": "Vinter/Vår"
    },
    {
        "id": "white_tailed_eagle",
        "type": "Rovfåglar",
        "nameEn": "White-tailed Eagle",
        "nameSv": "Havsörn",
        "scientific": "Haliaeetus albicilla",
        "rarity": 3,
        "funFact": "Sveriges nationsfågelstatus till trots räknas havsörnen som ett viltdjur och har gjort en enastående comeback.",
        "seasonDistribution": "Hela landet (kuster och sjöar)",
        "height": 40,
        "weight": 6000,
        "bestTime": "Dag"
    },
    {
        "id": "bat_common",
        "type": "Fladdermöss",
        "nameEn": "Common Pipistrelle",
        "nameSv": "Dvärgfladdermus",
        "scientific": "Pipistrellus pipistrellus",
        "rarity": 1,
        "funFact": "Dvärgfladdermusen väger bara 3–8 gram och kan äta 3000 myggor på en enda natt.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 5,
        "weight": 5,
        "bestTime": "Natt"
    },
    {
        "id": "common_toad",
        "type": "Groddjur",
        "nameEn": "Common Toad",
        "nameSv": "Åkergroda",
        "scientific": "Bufo bufo",
        "rarity": 1,
        "funFact": "Paddan återvänder varje år till samma lekvatten och kan leva i 30–40 år.",
        "seasonDistribution": "Hela landet",
        "height": 8,
        "weight": 50,
        "bestTime": "Natt (Vår)"
    },
    {
        "id": "grass_snake",
        "type": "Kräldjur",
        "nameEn": "Grass Snake",
        "nameSv": "Snok",
        "scientific": "Natrix natrix",
        "rarity": 1,
        "funFact": "Snoken är ofarlig och känns igen på det gula halsbandet. Den låtsas vara death när den hotas.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 10,
        "weight": 300,
        "bestTime": "Dag"
    },
    {
        "id": "common_viper",
        "type": "Kräldjur",
        "nameEn": "Common European Adder",
        "nameSv": "Huggorm",
        "scientific": "Vipera berus",
        "rarity": 2,
        "funFact": "Huggormen är den enda giftiga ormen i Sverige men är skygg och sällan farlig om man inte stör den.",
        "seasonDistribution": "Hela landet",
        "height": 10,
        "weight": 150,
        "bestTime": "Dag"
    }
];
