
// Comprehensive list of birds seen in Sweden (Regular breeding, migration, and common visitors)
// Classification follows standard Swedish taxonomy.
// Rarity Scale: 1 (Very Common) -> 5 (Very Rare / Casual Visitor)

window.swedishBirds = [
    {
        "id": "mute_swan",
        "type": "Andfåglar",
        "nameEn": "Mute Swan",
        "nameSv": "Knölsvan",
        "scientific": "Cygnus olor",
        "rarity": 1,
        "funFact": "Knölsvanen är en av världens tyngsta flygande fåglar.",
        "seasonDistribution": "Hela året (Södra/Mellersta Sverige)",
        "wingspan": 220,
        "eggs": 6,
        "weight": 11209,
        "color": "Blandad"
    },
    {
        "id": "whooper_swan",
        "type": "Andfåglar",
        "nameEn": "Whooper Swan",
        "nameSv": "Sångsvan",
        "scientific": "Cygnus cygnus",
        "rarity": 2,
        "funFact": "Sångsvanens rop liknar en trumpetstöt.",
        "seasonDistribution": "Hela året (Norra Sverige sommar / Södra vinter)",
        "wingspan": 235,
        "eggs": 5,
        "weight": 10723,
        "color": "Blandad"
    },
    {
        "id": "canada_goose",
        "type": "Andfåglar",
        "nameEn": "Canada Goose",
        "nameSv": "Kanadagås",
        "scientific": "Branta canadensis",
        "rarity": 1,
        "funFact": "Kanadagåsen introducerades i Sverige på 1930-talet.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 175,
        "eggs": 6,
        "weight": 4310,
        "color": "Blandad"
    },
    {
        "id": "greylag_goose",
        "type": "Andfåglar",
        "nameEn": "Greylag Goose",
        "nameSv": "Grågås",
        "scientific": "Anser anser",
        "rarity": 1,
        "funFact": "Grågåsen är stamfadern till de flesta tamgäss.",
        "seasonDistribution": "Sommar (Hela landet), Vinter (Södra Sverige)",
        "wingspan": 160,
        "eggs": 6,
        "weight": 4993,
        "color": "Grå"
    },
    {
        "id": "barnacle_goose",
        "type": "Andfåglar",
        "nameEn": "Barnacle Goose",
        "nameSv": "Vitkindad gås",
        "scientific": "Branta leucopsis",
        "rarity": 2,
        "funFact": "Vitkindad gås häckar numera ofta i stadsparker, inte bara i fjällen.",
        "seasonDistribution": "Sommar (Kuster & Parker)",
        "wingspan": 140,
        "eggs": 4,
        "weight": 2535,
        "color": "Vit"
    },
    {
        "id": "brent_goose",
        "type": "Andfåglar",
        "nameEn": "Brent Goose",
        "nameSv": "Prutgås",
        "scientific": "Branta bernicla",
        "rarity": 4,
        "funFact": "Prutgåsen flyttar långa sträckor och ses ofta sträcka längs kusterna.",
        "seasonDistribution": "Vår/Höst (Kuster)",
        "wingspan": 115,
        "eggs": 4,
        "weight": 2359,
        "color": "Blandad"
    },
    {
        "id": "mallard",
        "type": "Andfåglar",
        "nameEn": "Mallard",
        "nameSv": "Gräsand",
        "scientific": "Anas platyrhynchos",
        "rarity": 1,
        "funFact": "Gräsanden är vår vanligaste and och \"kvackandet\" kommer från honan.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 90,
        "eggs": 10,
        "weight": 1191,
        "color": "Blandad"
    },
    {
        "id": "common_teal",
        "type": "Andfåglar",
        "nameEn": "Common Teal",
        "nameSv": "Kricka",
        "scientific": "Anas crecca",
        "rarity": 2,
        "funFact": "Krickan är vår minsta simand.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 60,
        "eggs": 9,
        "weight": 525,
        "color": "Blandad"
    },
    {
        "id": "eurasian_wigeon",
        "type": "Andfåglar",
        "nameEn": "Eurasian Wigeon",
        "nameSv": "Bläsand",
        "scientific": "Anas penelope",
        "rarity": 2,
        "funFact": "Bläsandens hane visslar karakteristiskt \"vii-o\".",
        "seasonDistribution": "Sommar (Norra Sverige), Vår/Höst (Södra)",
        "wingspan": 80,
        "eggs": 8,
        "weight": 466,
        "color": "Blandad"
    },
    {
        "id": "tufted_duck",
        "type": "Andfåglar",
        "nameEn": "Tufted Duck",
        "nameSv": "Vigg",
        "scientific": "Aythya fuligula",
        "rarity": 1,
        "funFact": "Viggen känns igen på sin tofs i nacken.",
        "seasonDistribution": "Hela året (Kuster & Sjöar)",
        "wingspan": 70,
        "eggs": 9,
        "weight": 859,
        "color": "Blandad"
    },
    {
        "id": "common_goldeneye",
        "type": "Andfåglar",
        "nameEn": "Common Goldeneye",
        "nameSv": "Knipa",
        "scientific": "Bucephala clangula",
        "rarity": 2,
        "funFact": "Knipan häckar i håligheter i träd eller i holkar.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 77,
        "eggs": 9,
        "weight": 999,
        "color": "Blandad"
    },
    {
        "id": "common_eider",
        "type": "Andfåglar",
        "nameEn": "Common Eider",
        "nameSv": "Ejder",
        "scientific": "Somateria mollissima",
        "rarity": 2,
        "funFact": "Ejderns dun är känt för sin otroliga isoleringsförmåga.",
        "seasonDistribution": "Hela året (Kuster)",
        "wingspan": 100,
        "eggs": 5,
        "weight": 2591,
        "color": "Blandad"
    },
    {
        "id": "long_tailed_duck",
        "type": "Andfåglar",
        "nameEn": "Long-tailed Duck",
        "nameSv": "Alfågel",
        "scientific": "Clangula hyemalis",
        "rarity": 3,
        "funFact": "Alfågeln kallas ibland \"Gudunge\" för sitt vackra läte.",
        "seasonDistribution": "Vinter (Östersjön/Kuster)",
        "wingspan": 75,
        "eggs": 7,
        "weight": 831,
        "color": "Blandad"
    },
    {
        "id": "goosander",
        "type": "Andfåglar",
        "nameEn": "Goosander",
        "nameSv": "Storskrake",
        "scientific": "Mergus merganser",
        "rarity": 2,
        "funFact": "Storskraken har en sågtandad näbb för att fånga fisk.",
        "seasonDistribution": "Hela året (Sjöar & Kuster)",
        "wingspan": 95,
        "eggs": 9,
        "weight": 1187,
        "color": "Blandad"
    },
    {
        "id": "northern_shoveler",
        "type": "Andfåglar",
        "nameEn": "Northern Shoveler",
        "nameSv": "Skedand",
        "scientific": "Spatula clypeata",
        "rarity": 3,
        "funFact": "Skedanden har en enorm skedformad näbb för att sila vatten.",
        "seasonDistribution": "Sommar (Södra/Mellersta)",
        "wingspan": 80,
        "eggs": 10,
        "weight": 508,
        "color": "Blandad"
    },
    {
        "id": "gadwall",
        "type": "Andfåglar",
        "nameEn": "Gadwall",
        "nameSv": "Snatterand",
        "scientific": "Mareca strepera",
        "rarity": 3,
        "funFact": "Snatteranden är en diskret and som ökat på senare år.",
        "seasonDistribution": "Sommar (Södra)",
        "wingspan": 90,
        "eggs": 10,
        "weight": 639,
        "color": "Blandad"
    },
    {
        "id": "western_capercaillie",
        "type": "Hönsfåglar",
        "nameEn": "Western Capercaillie",
        "nameSv": "Tjäder",
        "scientific": "Tetrao urogallus",
        "rarity": 3,
        "funFact": "Tjädern är vår största skogshöna och känd för sitt tunga uppflog.",
        "seasonDistribution": "Hela året (Skogar)",
        "wingspan": 110,
        "eggs": 7,
        "weight": 3344,
        "color": "Blandad"
    },
    {
        "id": "black_grouse",
        "type": "Hönsfåglar",
        "nameEn": "Black Grouse",
        "nameSv": "Orre",
        "scientific": "Lyrurus tetrix",
        "rarity": 3,
        "funFact": "Orrens spel på mossar tidiga vårmorgnar är ett klassiskt skådespel.",
        "seasonDistribution": "Hela året (Skogar & Hed)",
        "wingspan": 80,
        "eggs": 8,
        "weight": 1286,
        "color": "Blandad"
    },
    {
        "id": "common_pheasant",
        "type": "Hönsfåglar",
        "nameEn": "Common Pheasant",
        "nameSv": "Fasan",
        "scientific": "Phasianus colchicus",
        "rarity": 2,
        "funFact": "Fasanen är en inplanterad art som ursprungligen kommer från Asien.",
        "seasonDistribution": "Hela året (Södra Sverige)",
        "wingspan": 80,
        "eggs": 10,
        "weight": 1006,
        "color": "Blandad"
    },
    {
        "id": "black_throated_loon",
        "type": "Lommar & Doppingar",
        "nameEn": "Black-throated Loon",
        "nameSv": "Storlom",
        "scientific": "Gavia arctica",
        "rarity": 3,
        "funFact": "Storlommen har ett klagande läte som hörs över sjöar på sommaren.",
        "seasonDistribution": "Sommar (Insjöar)",
        "wingspan": 120,
        "eggs": 2,
        "weight": 1532,
        "color": "Blandad"
    },
    {
        "id": "great_crested_grebe",
        "type": "Lommar & Doppingar",
        "nameEn": "Great Crested Grebe",
        "nameSv": "Skäggdopping",
        "scientific": "Podiceps cristatus",
        "rarity": 2,
        "funFact": "Skäggdoppingen bär sina ungar på ryggen när de är små.",
        "seasonDistribution": "Sommar (Sjöar & Kuster)",
        "wingspan": 89,
        "eggs": 4,
        "weight": 1781,
        "color": "Blandad"
    },
    {
        "id": "grey_heron",
        "type": "Hägrar",
        "nameEn": "Grey Heron",
        "nameSv": "Gråhäger",
        "scientific": "Ardea cinerea",
        "rarity": 1,
        "funFact": "Gråhägern står ofta blickstilla i vattnet och väntar på byte.",
        "seasonDistribution": "Hela året (Södra Sverige), Sommar (Norra)",
        "wingspan": 175,
        "eggs": 4,
        "weight": 1843,
        "color": "Grå"
    },
    {
        "id": "white_tailed_eagle",
        "type": "Rovfåglar",
        "nameEn": "White-tailed Eagle",
        "nameSv": "Havsörn",
        "scientific": "Haliaeetus albicilla",
        "rarity": 3,
        "funFact": "Havsörnen är Nordeuropas största rovfågel med ett vingspann upp till 2,5 meter.",
        "seasonDistribution": "Hela året (Kuster & Stora sjöar)",
        "wingspan": 220,
        "eggs": 2,
        "weight": 5880,
        "color": "Blandad"
    },
    {
        "id": "golden_eagle",
        "type": "Rovfåglar",
        "nameEn": "Golden Eagle",
        "nameSv": "Kungsörn",
        "scientific": "Aquila chrysaetos",
        "rarity": 4,
        "funFact": "Kungsörnen jagar ofta hare och räv i fjällvärlden.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 200,
        "eggs": 2,
        "weight": 5345,
        "color": "Blandad"
    },
    {
        "id": "western_osprey",
        "type": "Rovfåglar",
        "nameEn": "Western Osprey",
        "nameSv": "Fiskgjuse",
        "scientific": "Pandion haliaetus",
        "rarity": 2,
        "funFact": "Fiskgjusen är en mästare på att fånga fisk och dyker med fötterna före.",
        "seasonDistribution": "Sommar (Sjöar)",
        "wingspan": 160,
        "eggs": 3,
        "weight": 1740,
        "color": "Blandad"
    },
    {
        "id": "common_buzzard",
        "type": "Rovfåglar",
        "nameEn": "Common Buzzard",
        "nameSv": "Ormvråk",
        "scientific": "Buteo buteo",
        "rarity": 1,
        "funFact": "Ormvråken är Sveriges vanligaste rovfågel och ses ofta sitta på stolpar.",
        "seasonDistribution": "Hela året (Södra Sverige)",
        "wingspan": 120,
        "eggs": 3,
        "weight": 803,
        "color": "Blandad"
    },
    {
        "id": "eurasian_sparrowhawk",
        "type": "Rovfåglar",
        "nameEn": "Eurasian Sparrowhawk",
        "nameSv": "Sparvhök",
        "scientific": "Accipiter nisus",
        "rarity": 2,
        "funFact": "Sparvhöken är en skicklig jägare i tät skog och trädgårdar.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 70,
        "eggs": 5,
        "weight": 283,
        "color": "Blandad"
    },
    {
        "id": "northern_goshawk",
        "type": "Rovfåglar",
        "nameEn": "Northern Goshawk",
        "nameSv": "Duvhök",
        "scientific": "Accipiter gentilis",
        "rarity": 3,
        "funFact": "Duvhöken är betydligt större än sparvhöken och tar större byten.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 110,
        "eggs": 3,
        "weight": 718,
        "color": "Blandad"
    },
    {
        "id": "common_kestrel",
        "type": "Rovfåglar",
        "nameEn": "Common Kestrel",
        "nameSv": "Tornfalk",
        "scientific": "Falco tinnunculus",
        "rarity": 2,
        "funFact": "Tornfalken kan \"ryttla\", d.v.s. stå stilla i luften och spana efter sork.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 75,
        "eggs": 5,
        "weight": 194,
        "color": "Blandad"
    },
    {
        "id": "peregrine_falcon",
        "type": "Rovfåglar",
        "nameEn": "Peregrine Falcon",
        "nameSv": "Pilgrimsfalk",
        "scientific": "Falco peregrinus",
        "rarity": 4,
        "funFact": "Pilgrimsfalken är världens snabbaste djur när den dyker.",
        "seasonDistribution": "Hela året (Sällsynt, Kuster & Städer)",
        "wingspan": 100,
        "eggs": 3,
        "weight": 961,
        "color": "Blandad"
    },
    {
        "id": "western_marsh_harrier",
        "type": "Rovfåglar",
        "nameEn": "Western Marsh Harrier",
        "nameSv": "Brun kärrhök",
        "scientific": "Circus aeruginosus",
        "rarity": 3,
        "funFact": "Brun kärrhök seglar lågt över vassbälten med V-ställda vingar.",
        "seasonDistribution": "Sommar (Våtmarker)",
        "wingspan": 125,
        "eggs": 4,
        "weight": 906,
        "color": "Brun"
    },
    {
        "id": "eurasian_hobby",
        "type": "Rovfåglar",
        "nameEn": "Eurasian Hobby",
        "nameSv": "Lärkfalk",
        "scientific": "Falco subbuteo",
        "rarity": 3,
        "funFact": "Lärkfalken är en otroligt skicklig flygare som fångar trollsländor i luften.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 80,
        "eggs": 3,
        "weight": 247,
        "color": "Blandad"
    },
    {
        "id": "common_crane",
        "type": "Tranor & Rallar",
        "nameEn": "Common Crane",
        "nameSv": "Trana",
        "scientific": "Grus grus",
        "rarity": 2,
        "funFact": "Tranorna vid Hornborgasjön är ett säkert vårtecken.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 220,
        "eggs": 2,
        "weight": 4328,
        "color": "Blandad"
    },
    {
        "id": "eurasian_coot",
        "type": "Tranor & Rallar",
        "nameEn": "Eurasian Coot",
        "nameSv": "Sothöna",
        "scientific": "Fulica atra",
        "rarity": 1,
        "funFact": "Sothönan är helt svart med en vit panna och vita näbb.",
        "seasonDistribution": "Hela året (Södra Sverige)",
        "wingspan": 75,
        "eggs": 8,
        "weight": 770,
        "color": "Svart"
    },
    {
        "id": "eurasian_oystercatcher",
        "type": "Vadare",
        "nameEn": "Eurasian Oystercatcher",
        "nameSv": "Strandskata",
        "scientific": "Haematopus ostralegus",
        "rarity": 2,
        "funFact": "Strandskatan kan använda sin näbb för att öppna musslor.",
        "seasonDistribution": "Sommar (Kuster)",
        "wingspan": 83,
        "eggs": 3,
        "weight": 520,
        "color": "Blandad"
    },
    {
        "id": "northern_lapwing",
        "type": "Vadare",
        "nameEn": "Northern Lapwing",
        "nameSv": "Tofsvipa",
        "scientific": "Vanellus vanellus",
        "rarity": 1,
        "funFact": "Tofsvipan har en karakteristisk tofs på huvudet och rundade vingar.",
        "seasonDistribution": "Sommar (Jordbruksmark)",
        "wingspan": 85,
        "eggs": 4,
        "weight": 199,
        "color": "Blandad"
    },
    {
        "id": "eurasian_woodcock",
        "type": "Vadare",
        "nameEn": "Eurasian Woodcock",
        "nameSv": "Morkulla",
        "scientific": "Scolopax rusticola",
        "rarity": 3,
        "funFact": "Morkullan är aktiv i skymningen och har ögonen högt placerade på huvudet.",
        "seasonDistribution": "Sommar (Skogar)",
        "wingspan": 60,
        "eggs": 4,
        "weight": 281,
        "color": "Blandad"
    },
    {
        "id": "common_snipe",
        "type": "Vadare",
        "nameEn": "Common Snipe",
        "nameSv": "Enkelbeckasin",
        "scientific": "Gallinago gallinago",
        "rarity": 3,
        "funFact": "Enkelbeckasinens \"gnäggande\" läte skapas av vibrationer i stjärtpennorna.",
        "seasonDistribution": "Sommar (Våtmarker)",
        "wingspan": 45,
        "eggs": 4,
        "weight": 342,
        "color": "Blandad"
    },
    {
        "id": "eurasian_curlew",
        "type": "Vadare",
        "nameEn": "Eurasian Curlew",
        "nameSv": "Storspov",
        "scientific": "Numenius arquata",
        "rarity": 3,
        "funFact": "Storspoven har Sveriges längsta näbb.",
        "seasonDistribution": "Sommar (Jordbruksmark & Myrar)",
        "wingspan": 90,
        "eggs": 4,
        "weight": 819,
        "color": "Blandad"
    },
    {
        "id": "common_redshank",
        "type": "Vadare",
        "nameEn": "Common Redshank",
        "nameSv": "Rödbena",
        "scientific": "Tringa totanus",
        "rarity": 2,
        "funFact": "Rödbenan är mycket högljudd när man närmar sig dess revir.",
        "seasonDistribution": "Sommar (Kuster & Våtmarker)",
        "wingspan": 65,
        "eggs": 4,
        "weight": 133,
        "color": "Röd"
    },
    {
        "id": "black_headed_gull",
        "type": "Måsar & Tärnor",
        "nameEn": "Black-headed Gull",
        "nameSv": "Skrattmås",
        "scientific": "Chroicocephalus ridibundus",
        "rarity": 1,
        "funFact": "Skrattmåsen har mörkt chokladbrun huva på sommaren, inte svart.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 105,
        "eggs": 3,
        "weight": 389,
        "color": "Blandad"
    },
    {
        "id": "common_gull",
        "type": "Måsar & Tärnor",
        "nameEn": "Common Gull",
        "nameSv": "Fiskmås",
        "scientific": "Larus canus",
        "rarity": 1,
        "funFact": "Fiskmåsen är betydligt mindre och \"snällare\" i utseendet än trutarna.",
        "seasonDistribution": "Hela året (Kuster & Städer)",
        "wingspan": 115,
        "eggs": 3,
        "weight": 486,
        "color": "Blandad"
    },
    {
        "id": "herring_gull",
        "type": "Måsar & Tärnor",
        "nameEn": "Herring Gull",
        "nameSv": "Gråtrut",
        "scientific": "Larus argentatus",
        "rarity": 1,
        "funFact": "Gråtruten är en stor opportunist som äter allt från fisk till skräp.",
        "seasonDistribution": "Hela året (Kuster)",
        "wingspan": 140,
        "eggs": 3,
        "weight": 1219,
        "color": "Grå"
    },
    {
        "id": "great_black_backed_gull",
        "type": "Måsar & Tärnor",
        "nameEn": "Great Black-backed Gull",
        "nameSv": "Havstrut",
        "scientific": "Larus marinus",
        "rarity": 2,
        "funFact": "Havstruten är världens största trutart.",
        "seasonDistribution": "Hela året (Kuster)",
        "wingspan": 155,
        "eggs": 3,
        "weight": 1981,
        "color": "Blandad"
    },
    {
        "id": "arctic_tern",
        "type": "Måsar & Tärnor",
        "nameEn": "Arctic Tern",
        "nameSv": "Silvertärna",
        "scientific": "Sterna paradisaea",
        "rarity": 3,
        "funFact": "Silvertärnan gör en av djurvärldens längsta flyttningar, från Arktis till Antarktis.",
        "seasonDistribution": "Sommar (Norra Sverige & Kuster)",
        "wingspan": 80,
        "eggs": 2,
        "weight": 132,
        "color": "Blandad"
    },
    {
        "id": "common_tern",
        "type": "Måsar & Tärnor",
        "nameEn": "Common Tern",
        "nameSv": "Fisktärna",
        "scientific": "Sterna hirundo",
        "rarity": 2,
        "funFact": "Fisktärnan har en röd näbb med svart spets, till skillnad från silvertärnans helröda.",
        "seasonDistribution": "Sommar (Kuster & Sjöar)",
        "wingspan": 79,
        "eggs": 3,
        "weight": 103,
        "color": "Blandad"
    },
    {
        "id": "common_murre",
        "type": "Alkfåglar",
        "nameEn": "Common Murre",
        "nameSv": "Sillgrissla",
        "scientific": "Uria aalge",
        "rarity": 3,
        "funFact": "Sillgrisslan häckar i enorma fågelberg på Stora Karlsö.",
        "seasonDistribution": "Året runt (Östersjön)",
        "wingspan": 70,
        "eggs": 1,
        "weight": 807,
        "color": "Blandad"
    },
    {
        "id": "razorbill",
        "type": "Alkfåglar",
        "nameEn": "Razorbill",
        "nameSv": "Tordmule",
        "scientific": "Alca torda",
        "rarity": 3,
        "funFact": "Tordmulen har en hög, smal näbb med vita tvärstreck.",
        "seasonDistribution": "Året runt (Östersjön)",
        "wingspan": 65,
        "eggs": 1,
        "weight": 617,
        "color": "Blandad"
    },
    {
        "id": "black_guillemot",
        "type": "Alkfåglar",
        "nameEn": "Black Guillemot",
        "nameSv": "Tobisgrissla",
        "scientific": "Cepphus grylle",
        "rarity": 3,
        "funFact": "Tobisgrisslan har röda fötter och ett gap som lyser rött.",
        "seasonDistribution": "Året runt (Kuster)",
        "wingspan": 55,
        "eggs": 2,
        "weight": 955,
        "color": "Blandad"
    },
    {
        "id": "great_spotted_woodpecker",
        "type": "Hackspettar",
        "nameEn": "Great Spotted Woodpecker",
        "nameSv": "Större hackspett",
        "scientific": "Dendrocopos major",
        "rarity": 1,
        "funFact": "Större hackspett använder trummande mot träd för att markera revir.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 44,
        "eggs": 6,
        "weight": 97,
        "color": "Blandad"
    },
    {
        "id": "black_woodpecker",
        "type": "Hackspettar",
        "nameEn": "Black Woodpecker",
        "nameSv": "Spillkråka",
        "scientific": "Dryocopus martius",
        "rarity": 2,
        "funFact": "Spillkråkan är vår största hackspett och helt svart med röd hjässa.",
        "seasonDistribution": "Hela året (Skogar)",
        "wingspan": 70,
        "eggs": 4,
        "weight": 146,
        "color": "Blandad"
    },
    {
        "id": "european_green_woodpecker",
        "type": "Hackspettar",
        "nameEn": "European Green Woodpecker",
        "nameSv": "Gröngöling",
        "scientific": "Picus viridis",
        "rarity": 2,
        "funFact": "Gröngölingen ses ofta på marken där den letar efter myror.",
        "seasonDistribution": "Hela året (Södra/Mellersta Sverige)",
        "wingspan": 41,
        "eggs": 6,
        "weight": 229,
        "color": "Grön"
    },
    {
        "id": "tawny_owl",
        "type": "Ugglor",
        "nameEn": "Tawny Owl",
        "nameSv": "Kattuggla",
        "scientific": "Strix aluco",
        "rarity": 2,
        "funFact": "Det klassiska uggle-hoandet \"ho-hooo\" kommer ofta från kattugglan.",
        "seasonDistribution": "Hela året (Södra/Mellersta Sverige)",
        "wingspan": 96,
        "eggs": 4,
        "weight": 460,
        "color": "Blandad"
    },
    {
        "id": "eurasian_eagle_owl",
        "type": "Ugglor",
        "nameEn": "Eurasian Eagle-Owl",
        "nameSv": "Berguv",
        "scientific": "Bubo bubo",
        "rarity": 4,
        "funFact": "Berguven är en av världens största ugglor.",
        "seasonDistribution": "Hela året (Sällsynt)",
        "wingspan": 165,
        "eggs": 2,
        "weight": 2132,
        "color": "Blandad"
    },
    {
        "id": "common_wood_pigeon",
        "type": "Duvor",
        "nameEn": "Common Wood Pigeon",
        "nameSv": "Ringduva",
        "scientific": "Columba palumbus",
        "rarity": 1,
        "funFact": "Ringduvan är vår största duva och känns igen på det dova hoandet.",
        "seasonDistribution": "Sommar (Hela landet), Vinter (Södra)",
        "wingspan": 77,
        "eggs": 2,
        "weight": 503,
        "color": "Blandad"
    },
    {
        "id": "common_cuckoo",
        "type": "Övriga",
        "nameEn": "Common Cuckoo",
        "nameSv": "Gök",
        "scientific": "Cuculus canorus",
        "rarity": 2,
        "funFact": "Göken lägger sina ägg i andra fåglars bon (boparasitism).",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 60,
        "eggs": 10,
        "weight": 41,
        "color": "Blandad"
    },
    {
        "id": "common_swift",
        "type": "Övriga",
        "nameEn": "Common Swift",
        "nameSv": "Tornseglare",
        "scientific": "Apus apus",
        "rarity": 1,
        "funFact": "Tornseglaren sover, äter och parar sig i flykten och landar sällan.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 42,
        "eggs": 3,
        "weight": 61,
        "color": "Blandad"
    },
    {
        "id": "willow_warbler",
        "type": "Sångare",
        "nameEn": "Willow Warbler",
        "nameSv": "Lövsångare",
        "scientific": "Phylloscopus trochilus",
        "rarity": 1,
        "funFact": "Lövsångaren är troligen Sveriges talrikaste fågel.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 19,
        "eggs": 6,
        "weight": 20,
        "color": "Blandad"
    },
    {
        "id": "common_chiffchaff",
        "type": "Sångare",
        "nameEn": "Common Chiffchaff",
        "nameSv": "Gransångare",
        "scientific": "Phylloscopus collybita",
        "rarity": 2,
        "funFact": "Gransångaren sjunger sitt namn: \"silt-sult-silt-sult\".",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 18,
        "eggs": 5,
        "weight": 32,
        "color": "Blandad"
    },
    {
        "id": "eurasian_blackcap",
        "type": "Sångare",
        "nameEn": "Eurasian Blackcap",
        "nameSv": "Svarthätta",
        "scientific": "Sylvia atricapilla",
        "rarity": 2,
        "funFact": "Svarthättans sång är vacker och flöjtande.",
        "seasonDistribution": "Sommar (Södra/Mellersta Sverige)",
        "wingspan": 23,
        "eggs": 5,
        "weight": 27,
        "color": "Svart"
    },
    {
        "id": "goldcrest",
        "type": "Sångare",
        "nameEn": "Goldcrest",
        "nameSv": "Kungsfågel",
        "scientific": "Regulus regulus",
        "rarity": 2,
        "funFact": "Kungsfågeln är Sveriges (och Europas) minsta fågel.",
        "seasonDistribution": "Hela året (Södra/Mellersta Sverige)",
        "wingspan": 14,
        "eggs": 10,
        "weight": 8,
        "color": "Blandad"
    },
    {
        "id": "garden_warbler",
        "type": "Sångare",
        "nameEn": "Garden Warbler",
        "nameSv": "Trädgårdssångare",
        "scientific": "Sylvia borin",
        "rarity": 2,
        "funFact": "Trädgårdssångaren har en vacker porlande sång men är väldigt oansenlig till utseendet.",
        "seasonDistribution": "Sommar (Lövskog)",
        "wingspan": 22,
        "eggs": 5,
        "weight": 26,
        "color": "Blandad"
    },
    {
        "id": "lesser_whitethroat",
        "type": "Sångare",
        "nameEn": "Lesser Whitethroat",
        "nameSv": "Ärtsångare",
        "scientific": "Sylvia curruca",
        "rarity": 2,
        "funFact": "Ärtsångarens solog \"rull-rull-rull\" låter som torra ärtor som skakas.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 19,
        "eggs": 5,
        "weight": 17,
        "color": "Blandad"
    },
    {
        "id": "common_whitethroat",
        "type": "Sångare",
        "nameEn": "Common Whitethroat",
        "nameSv": "Törnsångare",
        "scientific": "Sylvia communis",
        "rarity": 2,
        "funFact": "Törnsångaren gör ofta en liten sångflykt från en busktopp.",
        "seasonDistribution": "Sommar (Öppna marker)",
        "wingspan": 23,
        "eggs": 5,
        "weight": 20,
        "color": "Blandad"
    },
    {
        "id": "common_blackbird",
        "type": "Trastar",
        "nameEn": "Common Blackbird",
        "nameSv": "Koltrast",
        "scientific": "Turdus merula",
        "rarity": 1,
        "funFact": "Koltrasten har röstats fram till Sveriges nationalfågel.",
        "seasonDistribution": "Hela året (Södra, Sommar Norra)",
        "wingspan": 36,
        "eggs": 4,
        "weight": 108,
        "color": "Blandad"
    },
    {
        "id": "song_thrush",
        "type": "Trastar",
        "nameEn": "Song Thrush",
        "nameSv": "Taltrast",
        "scientific": "Turdus philomelos",
        "rarity": 1,
        "funFact": "Taltrasten upprepar ofta sina strofer 2-3 gånger.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 34,
        "eggs": 5,
        "weight": 66,
        "color": "Blandad"
    },
    {
        "id": "fieldfare",
        "type": "Trastar",
        "nameEn": "Fieldfare",
        "nameSv": "Björktrast",
        "scientific": "Turdus pilaris",
        "rarity": 1,
        "funFact": "Björktrasten försvarar sina bon aggressivt, ibland genom att \"skita ner\" inkräktare.",
        "seasonDistribution": "Hela året (Södra/Mellersta)",
        "wingspan": 40,
        "eggs": 6,
        "weight": 93,
        "color": "Blandad"
    },
    {
        "id": "redwing",
        "type": "Trastar",
        "nameEn": "Redwing",
        "nameSv": "Rödvingetrast",
        "scientific": "Turdus iliacus",
        "rarity": 2,
        "funFact": "Rödvingetrasten har en tydlig röd fläck under vingen.",
        "seasonDistribution": "Sommar (Norra Sverige), Flyttar",
        "wingspan": 34,
        "eggs": 5,
        "weight": 86,
        "color": "Röd"
    },
    {
        "id": "european_robin",
        "type": "Trastar",
        "nameEn": "European Robin",
        "nameSv": "Rödhake",
        "scientific": "Erithacus rubecula",
        "rarity": 1,
        "funFact": "Rödhaken är nyfiken och orädd, ofta kallad \"trädgårdsmästarens vän\".",
        "seasonDistribution": "Sommar (Hela landet), Vinter (Södra)",
        "wingspan": 21,
        "eggs": 6,
        "weight": 79,
        "color": "Röd"
    },
    {
        "id": "great_tit",
        "type": "Mesar",
        "nameEn": "Great Tit",
        "nameSv": "Talgoxe",
        "scientific": "Parus major",
        "rarity": 1,
        "funFact": "Talgoxen är en av fågelbordets tuffaste gäster.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 24,
        "eggs": 8,
        "weight": 21,
        "color": "Blandad"
    },
    {
        "id": "eurasian_blue_tit",
        "type": "Mesar",
        "nameEn": "Eurasian Blue Tit",
        "nameSv": "Blåmes",
        "scientific": "Cyanistes caeruleus",
        "rarity": 1,
        "funFact": "Blåmesen är en akrobat som ofta hänger upp och ner i grenar.",
        "seasonDistribution": "Hela året (Södra/Mellersta)",
        "wingspan": 18,
        "eggs": 10,
        "weight": 12,
        "color": "Blå"
    },
    {
        "id": "coal_tit",
        "type": "Mesar",
        "nameEn": "Coal Tit",
        "nameSv": "Svartmes",
        "scientific": "Periparus ater",
        "rarity": 2,
        "funFact": "Svartmesen har en vit nackfläck som skiljer den från talltitan.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 18,
        "eggs": 9,
        "weight": 23,
        "color": "Svart"
    },
    {
        "id": "crested_tit",
        "type": "Mesar",
        "nameEn": "Crested Tit",
        "nameSv": "Tofsmes",
        "scientific": "Lophophanes cristatus",
        "rarity": 2,
        "funFact": "Tofsmesen är starkt bunden till barrskog.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 20,
        "eggs": 5,
        "weight": 32,
        "color": "Blandad"
    },
    {
        "id": "common_chaffinch",
        "type": "Finkar",
        "nameEn": "Common Chaffinch",
        "nameSv": "Bofink",
        "scientific": "Fringilla coelebs",
        "rarity": 1,
        "funFact": "Bofinken är en av Sveriges absolut vanligaste fåglar.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 26,
        "eggs": 5,
        "weight": 16,
        "color": "Blandad"
    },
    {
        "id": "brambling",
        "type": "Finkar",
        "nameEn": "Brambling",
        "nameSv": "Bergfink",
        "scientific": "Fringilla montifringilla",
        "rarity": 2,
        "funFact": "Bergfinken häckar i norr men ses i enorma flockar söderut på vintern.",
        "seasonDistribution": "Vinter (Södra), Sommar (Norra)",
        "wingspan": 26,
        "eggs": 6,
        "weight": 29,
        "color": "Blandad"
    },
    {
        "id": "eurasian_bullfinch",
        "type": "Finkar",
        "nameEn": "Eurasian Bullfinch",
        "nameSv": "Domherre",
        "scientific": "Pyrrhula pyrrhula",
        "rarity": 2,
        "funFact": "Domherren är en klassisk julkortsfågel.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 26,
        "eggs": 5,
        "weight": 35,
        "color": "Röd"
    },
    {
        "id": "european_greenfinch",
        "type": "Finkar",
        "nameEn": "European Greenfinch",
        "nameSv": "Grönfink",
        "scientific": "Chloris chloris",
        "rarity": 1,
        "funFact": "Grönfinken har en kraftig näbb för att knäcka frön.",
        "seasonDistribution": "Hela året (Södra/Mellersta)",
        "wingspan": 26,
        "eggs": 5,
        "weight": 35,
        "color": "Grön"
    },
    {
        "id": "european_goldfinch",
        "type": "Finkar",
        "nameEn": "European Goldfinch",
        "nameSv": "Steglits",
        "scientific": "Carduelis carduelis",
        "rarity": 2,
        "funFact": "Steglitsen har ett mycket färgglatt ansikte i rött, vitt och svart.",
        "seasonDistribution": "Hela året (Södra Sverige)",
        "wingspan": 23,
        "eggs": 5,
        "weight": 15,
        "color": "Blandad"
    },
    {
        "id": "eurasian_siskin",
        "type": "Finkar",
        "nameEn": "Eurasian Siskin",
        "nameSv": "Grönsiska",
        "scientific": "Spinus spinus",
        "rarity": 2,
        "funFact": "Grönsiskan klättrar ofta vig som en mes i björkar och alar.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 21,
        "eggs": 5,
        "weight": 20,
        "color": "Grön"
    },
    {
        "id": "house_sparrow",
        "type": "Sparvar",
        "nameEn": "House Sparrow",
        "nameSv": "Gråsparv",
        "scientific": "Passer domesticus",
        "rarity": 1,
        "funFact": "Gråsparven har följt människan i tusentals år.",
        "seasonDistribution": "Hela året (Bebyggelse)",
        "wingspan": 23,
        "eggs": 4,
        "weight": 22,
        "color": "Grå"
    },
    {
        "id": "eurasian_tree_sparrow",
        "type": "Sparvar",
        "nameEn": "Eurasian Tree Sparrow",
        "nameSv": "Pilfink",
        "scientific": "Passer montanus",
        "rarity": 1,
        "funFact": "Pilfinken har en svart fläck på den vita kinden, vilket skiljer den från gråsparven.",
        "seasonDistribution": "Hela året (Bebyggelse)",
        "wingspan": 21,
        "eggs": 5,
        "weight": 17,
        "color": "Blandad"
    },
    {
        "id": "yellowhammer",
        "type": "Sparvar",
        "nameEn": "Yellowhammer",
        "nameSv": "Gulsparv",
        "scientific": "Emberiza citrinella",
        "rarity": 1,
        "funFact": "Gulsparvens sång brukar beskrivas som att den räknar till sju: \"en-två-tre-fyr-fem-sex-sjuuu\".",
        "seasonDistribution": "Hela året (Jordbruksmark)",
        "wingspan": 26,
        "eggs": 4,
        "weight": 35,
        "color": "Gul"
    },
    {
        "id": "reed_bunting",
        "type": "Sparvar",
        "nameEn": "Reed Bunting",
        "nameSv": "Sävsparv",
        "scientific": "Emberiza schoeniclus",
        "rarity": 2,
        "funFact": "Sävsparven ses ofta sjunga från ett vassrör.",
        "seasonDistribution": "Sommar (Våtmarker)",
        "wingspan": 23,
        "eggs": 5,
        "weight": 24,
        "color": "Blandad"
    },
    {
        "id": "hooded_crow",
        "type": "Kråkfåglar",
        "nameEn": "Hooded Crow",
        "nameSv": "Gråkråka",
        "scientific": "Corvus cornix",
        "rarity": 1,
        "funFact": "Gråkråkor är mycket intelligenta och kan lösa komplexa problem.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 98,
        "eggs": 4,
        "weight": 550,
        "color": "Grå"
    },
    {
        "id": "eurasian_jackdaw",
        "type": "Kråkfåglar",
        "nameEn": "Eurasian Jackdaw",
        "nameSv": "Kaja",
        "scientific": "Coloeus monedula",
        "rarity": 1,
        "funFact": "Kajor lever i par som håller ihop hela livet och är mycket sociala.",
        "seasonDistribution": "Hela året (Södra/Mellersta)",
        "wingspan": 67,
        "eggs": 4,
        "weight": 311,
        "color": "Blandad"
    },
    {
        "id": "eurasian_magpie",
        "type": "Kråkfåglar",
        "nameEn": "Eurasian Magpie",
        "nameSv": "Skata",
        "scientific": "Pica pica",
        "rarity": 1,
        "funFact": "Skatan är känd för att samla på blanka föremål (en myt, men den är nyfiken).",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 56,
        "eggs": 6,
        "weight": 247,
        "color": "Blandad"
    },
    {
        "id": "eurasian_jay",
        "type": "Kråkfåglar",
        "nameEn": "Eurasian Jay",
        "nameSv": "Nötskrika",
        "scientific": "Garrulus glandarius",
        "rarity": 2,
        "funFact": "Nötskrikan planterar ekar genom att glömma bort gömda ollon.",
        "seasonDistribution": "Hela året (Skogar)",
        "wingspan": 55,
        "eggs": 5,
        "weight": 248,
        "color": "Blandad"
    },
    {
        "id": "common_raven",
        "type": "Kråkfåglar",
        "nameEn": "Common Raven",
        "nameSv": "Korp",
        "scientific": "Corvus corax",
        "rarity": 2,
        "funFact": "Korpen är Sveriges största tätting och en mästare på flygakrobatik.",
        "seasonDistribution": "Hela året (Hela landet)",
        "wingspan": 130,
        "eggs": 5,
        "weight": 1240,
        "color": "Blandad"
    },
    {
        "id": "barn_swallow",
        "type": "Svalor",
        "nameEn": "Barn Swallow",
        "nameSv": "Ladusvala",
        "scientific": "Hirundo rustica",
        "rarity": 1,
        "funFact": "Ladusvalan har långa spröt på stjärten och häckar gärna inomhus i lador.",
        "seasonDistribution": "Sommar (Landsbygd)",
        "wingspan": 33,
        "eggs": 4,
        "weight": 15,
        "color": "Blandad"
    },
    {
        "id": "common_house_martin",
        "type": "Svalor",
        "nameEn": "Common House Martin",
        "nameSv": "Hussvala",
        "scientific": "Delichon urbicum",
        "rarity": 1,
        "funFact": "Hussvalan bygger sitt bo av lera under taknocken.",
        "seasonDistribution": "Sommar (Bebyggelse)",
        "wingspan": 28,
        "eggs": 4,
        "weight": 25,
        "color": "Blandad"
    },
    {
        "id": "sand_martin",
        "type": "Svalor",
        "nameEn": "Sand Martin",
        "nameSv": "Backsvala",
        "scientific": "Riparia riparia",
        "rarity": 2,
        "funFact": "Backsvalan gräver långa gångar i sandbranter för sitt bo.",
        "seasonDistribution": "Sommar (Grustag & Branter)",
        "wingspan": 27,
        "eggs": 5,
        "weight": 27,
        "color": "Blandad"
    },
    {
        "id": "white_wagtail",
        "type": "Övriga",
        "nameEn": "White Wagtail",
        "nameSv": "Sädesärla",
        "scientific": "Motacilla alba",
        "rarity": 1,
        "funFact": "Sädesärlans ankomst ses av många som det riktiga vårtecknet.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 28,
        "eggs": 5,
        "weight": 24,
        "color": "Blandad"
    },
    {
        "id": "eurasian_wren",
        "type": "Övriga",
        "nameEn": "Eurasian Wren",
        "nameSv": "Gärdsmyg",
        "scientific": "Troglodytes troglodytes",
        "rarity": 2,
        "funFact": "Gärdsmygen ser ut som en liten mörk boll med upprättstående stjärt.",
        "seasonDistribution": "Hela året (Södra/Mellersta)",
        "wingspan": 15,
        "eggs": 6,
        "weight": 69,
        "color": "Blandad"
    },
    {
        "id": "common_starling",
        "type": "Övriga",
        "nameEn": "Common Starling",
        "nameSv": "Stare",
        "scientific": "Sturnus vulgaris",
        "rarity": 1,
        "funFact": "Starar kan bilda enorma flockar (\"sort sol\") vid flyttning.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 40,
        "eggs": 5,
        "weight": 18,
        "color": "Blandad"
    },
    {
        "id": "bohemian_waxwing",
        "type": "Övriga",
        "nameEn": "Bohemian Waxwing",
        "nameSv": "Sidensvans",
        "scientific": "Bombycilla garrulus",
        "rarity": 3,
        "funFact": "Sidensvansen dyker upp i städerna på vintern för att äta rönnbär.",
        "seasonDistribution": "Vinter (Hela landet)",
        "wingspan": 34,
        "eggs": 5,
        "weight": 94,
        "color": "Blandad"
    },
    {
        "id": "meadow_pipit",
        "type": "Övriga",
        "nameEn": "Meadow Pipit",
        "nameSv": "Ängspiplärka",
        "scientific": "Anthus pratensis",
        "rarity": 2,
        "funFact": "Ängspiplärkan är en av fjällvärldens vanligaste fåglar.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 24,
        "eggs": 4,
        "weight": 19,
        "color": "Blandad"
    },
    {
        "id": "tree_pipit",
        "type": "Övriga",
        "nameEn": "Tree Pipit",
        "nameSv": "Trädpiplärka",
        "scientific": "Anthus trivialis",
        "rarity": 2,
        "funFact": "Trädpiplärkan flyger upp från en trädtopp och dalar ner som en fallskärm medan den sjunger.",
        "seasonDistribution": "Sommar (Skogsbryn)",
        "wingspan": 26,
        "eggs": 4,
        "weight": 54,
        "color": "Blandad"
    },
    {
        "id": "european_pied_flycatcher",
        "type": "Övriga",
        "nameEn": "European Pied Flycatcher",
        "nameSv": "Svartvit flugsnappare",
        "scientific": "Ficedula hypoleuca",
        "rarity": 2,
        "funFact": "Svartvit flugsnappare är en av de vanligaste hyresgästerna i fågelholkar.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 22,
        "eggs": 6,
        "weight": 87,
        "color": "Svart"
    },
    {
        "id": "spotted_flycatcher",
        "type": "Övriga",
        "nameEn": "Spotted Flycatcher",
        "nameSv": "Grå flugsnappare",
        "scientific": "Muscicapa striata",
        "rarity": 2,
        "funFact": "Grå flugsnappare sitter ofta helt öppet och gör utfall mot insekter.",
        "seasonDistribution": "Sommar (Hela landet)",
        "wingspan": 24,
        "eggs": 4,
        "weight": 30,
        "color": "Grå"
    }
];
