
// List of Swedish Fish (Fiskboken)
window.swedishFish = [
    {
        "id": "northern_pike",
        "type": "Rovfisk",
        "nameEn": "Northern Pike",
        "nameSv": "Gädda",
        "scientific": "Esox lucius",
        "rarity": 1,
        "funFact": "Gäddan kan ha upp till 700 tänder och är en av Sveriges vanligaste rovfiskar.",
        "seasonDistribution": "Hela landet (Sjöar & Kuster)",
        "length": 100, // cm
        "weight": 10000, // g
        "bestTime": "Året runt"
    },
    {
        "id": "european_perch",
        "type": "Abborrfiskar",
        "nameEn": "European Perch",
        "nameSv": "Abborre",
        "scientific": "Perca fluviatilis",
        "rarity": 1,
        "funFact": "Abborren är Sveriges nationalfisk och finns i nästan alla insjöar och kustvatten.",
        "seasonDistribution": "Hela landet",
        "length": 30,
        "weight": 500,
        "bestTime": "Sommar/Höst"
    },
    {
        "id": "atlantic_herring",
        "type": "Sillfiskar",
        "nameEn": "Atlantic Herring",
        "nameSv": "Sill",
        "scientific": "Clupea harengus",
        "rarity": 1,
        "funFact": "Sill kallas strömming i Östersjön. Surströmming görs av fermenterad östersjöströmming.",
        "seasonDistribution": "Kuster",
        "length": 30,
        "weight": 200,
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "atlantic_cod",
        "type": "Torskfiskar",
        "nameEn": "Atlantic Cod",
        "nameSv": "Torsk",
        "scientific": "Gadus morhua",
        "rarity": 2,
        "funFact": "Torsken har en skäggtöm på hakan för att känna av botten och sina bytesdjur.",
        "seasonDistribution": "Västerhavet & Östersjön",
        "length": 80,
        "weight": 4000,
        "bestTime": "Vinter"
    },
    {
        "id": "brown_trout",
        "type": "Laxfiskar",
        "nameEn": "Brown Trout",
        "nameSv": "Öring",
        "scientific": "Salmo trutta",
        "rarity": 2,
        "funFact": "Öringen kan leva i havet (havsöring) eller i bäckar (bäcköring) – samma art, olika livsstil.",
        "seasonDistribution": "Hela landet",
        "length": 60,
        "weight": 3000,
        "bestTime": "Höst"
    },
    {
        "id": "atlantic_salmon",
        "type": "Laxfiskar",
        "nameEn": "Atlantic Salmon",
        "nameSv": "Lax",
        "scientific": "Salmo salar",
        "rarity": 2,
        "funFact": "Laxen vandrar uppför sina födelseälvar för att leka – ibland hundratals kilometer mot strömmen.",
        "seasonDistribution": "Kuster & Älvar",
        "length": 100,
        "weight": 8000,
        "bestTime": "Sommar/Höst"
    },
    {
        "id": "arctic_char",
        "type": "Laxfiskar",
        "nameEn": "Arctic Char",
        "nameSv": "Röding",
        "scientific": "Salvelinus alpinus",
        "rarity": 2,
        "funFact": "Rödingen är en relikt från istiden och lever i djupa, kalla fjällsjöar i norra Sverige.",
        "seasonDistribution": "Norra Sverige (fjällsjöar)",
        "length": 50,
        "weight": 2000,
        "bestTime": "Sommar"
    },
    {
        "id": "whitefish",
        "type": "Laxfiskar",
        "nameEn": "Vendace / Whitefish",
        "nameSv": "Siklöja",
        "scientific": "Coregonus albula",
        "rarity": 1,
        "funFact": "Siklöjans rom (löjrom) från Kalix är en delikatess med skyddad geografisk beteckning i EU.",
        "seasonDistribution": "Norra Sverige",
        "length": 20,
        "weight": 100,
        "bestTime": "Höst/Vinter"
    },
    {
        "id": "common_bream",
        "type": "Karpfiskar",
        "nameEn": "Common Bream",
        "nameSv": "Braxen",
        "scientific": "Abramis brama",
        "rarity": 1,
        "funFact": "Braxen har en hög, tillplattad kropp och gillar grunda, varma sjöar med mjuk botten.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "length": 45,
        "weight": 2000,
        "bestTime": "Sommar"
    },
    {
        "id": "roach",
        "type": "Karpfiskar",
        "nameEn": "Roach",
        "nameSv": "Mört",
        "scientific": "Rutilus rutilus",
        "rarity": 1,
        "funFact": "Mörten är en av Sveriges vanligaste fiskar och kan vara svår att skilja från andra karpfiskar.",
        "seasonDistribution": "Hela landet",
        "length": 25,
        "weight": 300,
        "bestTime": "Sommar"
    },
    {
        "id": "rudd",
        "type": "Karpfiskar",
        "nameEn": "Rudd",
        "nameSv": "Sarv",
        "scientific": "Scardinius erythrophthalmus",
        "rarity": 2,
        "funFact": "Sarven har röda fenor och gyllene ögon – lätt att förväxla med mörten men gillar ytvannet mer.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "length": 25,
        "weight": 400,
        "bestTime": "Sommar"
    },
    {
        "id": "common_carp",
        "type": "Karpfiskar",
        "nameEn": "Common Carp",
        "nameSv": "Karp",
        "scientific": "Cyprinus carpio",
        "rarity": 2,
        "funFact": "Karpen kan bli över 40 år gammal och väga mer än 30 kg. Den är ursprungligen importerad till Sverige.",
        "seasonDistribution": "Södra Sverige",
        "length": 80,
        "weight": 5000,
        "bestTime": "Sommar"
    },
    {
        "id": "tench",
        "type": "Karpfiskar",
        "nameEn": "Tench",
        "nameSv": "Sutare",
        "scientific": "Tinca tinca",
        "rarity": 2,
        "funFact": "Sutaren kallas 'läkarfisken' i folktron – man trodde att andra fiskar botas av att gnida sig mot dess slemhud.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "length": 40,
        "weight": 1500,
        "bestTime": "Sommar"
    },
    {
        "id": "pike_perch",
        "type": "Abborrfiskar",
        "nameEn": "Pike-perch / Zander",
        "nameSv": "Gös",
        "scientific": "Sander lucioperca",
        "rarity": 2,
        "funFact": "Gösen har kattögon som reflekterar ljuset och kan jaga effektivt i mörkt vatten.",
        "seasonDistribution": "Hela landet",
        "length": 70,
        "weight": 3000,
        "bestTime": "Sommar/Höst"
    },
    {
        "id": "burbot",
        "type": "Torskfiskar",
        "nameEn": "Burbot",
        "nameSv": "Lake",
        "scientific": "Lota lota",
        "rarity": 2,
        "funFact": "Laken är den enda sötvattensfisk som tillhör torskfamiljen och leker under isen på vintern.",
        "seasonDistribution": "Hela landet",
        "length": 60,
        "weight": 2000,
        "bestTime": "Vinter"
    },
    {
        "id": "wels_catfish",
        "type": "Malartade fiskar",
        "nameEn": "Wels Catfish",
        "nameSv": "Mal",
        "scientific": "Silurus glanis",
        "rarity": 3,
        "funFact": "Malen är Europas största sötvattensfisk och kan bli 3 meter lång och väga mer än 200 kg.",
        "seasonDistribution": "Södra Sverige (få lokaler)",
        "length": 150,
        "weight": 30000,
        "bestTime": "Sommar"
    },
    {
        "id": "asp",
        "type": "Karpfiskar",
        "nameEn": "Asp",
        "nameSv": "Asp",
        "scientific": "Leuciscus aspius",
        "rarity": 3,
        "funFact": "Aspen är en av de få karpfiskarna som är rovfisk och aktivt jagar spiggfiskar vid ytan.",
        "seasonDistribution": "Södra Sverige",
        "length": 60,
        "weight": 2000,
        "bestTime": "Sommar"
    },
    {
        "id": "ide",
        "type": "Karpfiskar",
        "nameEn": "Ide / Orfe",
        "nameSv": "Id",
        "scientific": "Leuciscus idus",
        "rarity": 2,
        "funFact": "Idarna är kända för sina spektakulära lekvandringar på våren i forsande åar.",
        "seasonDistribution": "Hela landet",
        "length": 50,
        "weight": 1500,
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "european_eel",
        "type": "Ålfiskar",
        "nameEn": "European Eel",
        "nameSv": "Ål",
        "scientific": "Anguilla anguilla",
        "rarity": 3,
        "funFact": "Ålen föds i Sargassohavet och vandrar tusentals mil till Europa – dess lekplats var okänd till 1900-talet.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "length": 100,
        "weight": 1500,
        "bestTime": "Sommar/Höst"
    },
    {
        "id": "sprat",
        "type": "Sillfiskar",
        "nameEn": "Sprat",
        "nameSv": "Skarpsill",
        "scientific": "Sprattus sprattus",
        "rarity": 1,
        "funFact": "Skarpsillen är basen för det välkända ansjovisinläggningen – 'ansjovis' i Sverige är egentligen skarpsill.",
        "seasonDistribution": "Östersjön & Västerhavet",
        "length": 12,
        "weight": 15,
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "mackerel",
        "type": "Makrillfiskar",
        "nameEn": "Atlantic Mackerel",
        "nameSv": "Makrill",
        "scientific": "Scomber scombrus",
        "rarity": 1,
        "funFact": "Makrillens blixtsnabba simförmåga och gnistrande färger gör den till en favorit bland sportfiskare.",
        "seasonDistribution": "Västerhavet (kuster)",
        "length": 35,
        "weight": 400,
        "bestTime": "Sommar"
    },
    {
        "id": "three_spined_stickleback",
        "type": "Stickelfiskar",
        "nameEn": "Three-spined Stickleback",
        "nameSv": "Storspigg",
        "scientific": "Gasterosteus aculeatus",
        "rarity": 1,
        "funFact": "Den lille storrpiggformen hanen bygger ett bo av växtdelar och vaktar äggen med nit – klassisk karaktär i ekologin.",
        "seasonDistribution": "Hela landet",
        "length": 8,
        "weight": 5,
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "sea_trout",
        "type": "Laxfiskar",
        "nameEn": "Sea Trout",
        "nameSv": "Havsöring",
        "scientific": "Salmo trutta trutta",
        "rarity": 2,
        "funFact": "Havsöringen leker i sötvatten men tillbringar sin tillväxtfas i havet – en vandringsfisk av rang.",
        "seasonDistribution": "Kuster & Älvar",
        "length": 70,
        "weight": 4000,
        "bestTime": "Höst"
    },
    {
        "id": "garfish",
        "type": "Nålfiskar",
        "nameEn": "Garfish",
        "nameSv": "Hornfisk",
        "scientific": "Belone belone",
        "rarity": 2,
        "funFact": "Hornfiskens ben är gröna på grund av biliverdin – men köttet är helt ätbart och delikat.",
        "seasonDistribution": "Västerhavet & södra Östersjön",
        "length": 70,
        "weight": 400,
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "plaice",
        "type": "Platfiskar",
        "nameEn": "European Plaice",
        "nameSv": "Rödspätta",
        "scientific": "Pleuronectes platessa",
        "rarity": 2,
        "funFact": "Rödspättan har orange prickar och båda ögonen på höger sida – den plattas till och kamouflerar sig på botten.",
        "seasonDistribution": "Västerhavet",
        "length": 50,
        "weight": 2000,
        "bestTime": "Sommar"
    },
    {
        "id": "flounder",
        "type": "Platfiskar",
        "nameEn": "European Flounder",
        "nameSv": "Skrubbskädda",
        "scientific": "Platichthys flesus",
        "rarity": 1,
        "funFact": "Skrubbskäddan kan finnas i sötvatten och är en av de mest euryhalina fiskarna – tål allt från sött till salt.",
        "seasonDistribution": "Kuster (hela).",
        "length": 40,
        "weight": 1500,
        "bestTime": "Sommar"
    },
    {
        "id": "vendace",
        "type": "Laxfiskar",
        "nameEn": "Vendace",
        "nameSv": "Sik",
        "scientific": "Coregonus lavaretus",
        "rarity": 1,
        "funFact": "Sikens smak varierar kraftigt beroende på vilket vatten den lever i – kustens sik är en delikatess.",
        "seasonDistribution": "Hela landet",
        "length": 40,
        "weight": 800,
        "bestTime": "Höst"
    },
    {
        "id": "rainbow_trout",
        "type": "Laxfiskar",
        "nameEn": "Rainbow Trout",
        "nameSv": "Regnbågslax",
        "scientific": "Oncorhynchus mykiss",
        "rarity": 2,
        "funFact": "Ursprungligen från Nordamerika men utsätts i svenska vatten och är populär bland sportfiskare.",
        "seasonDistribution": "Södra och mellersta Sverige (odlad/utplanterad)",
        "length": 60,
        "weight": 3000,
        "bestTime": "Vår/Höst"
    }
];
