
// List of Swedish Wildflowers (Blomboken)
window.swedishFlowers = [
    {
        "id": "wood_anemone",
        "type": "Vårblommor",
        "nameEn": "Wood Anemone",
        "nameSv": "Vitsippa",
        "scientific": "Anemone nemorosa",
        "rarity": 1,
        "funFact": "Vitsippan är ett av de säkraste vårtecknen i Sverige – den dyker upp i april och täcker hela skogsmarken.",
        "seasonDistribution": "Hela landet",
        "height": 15, // cm
        "color": "Vit",
        "bestTime": "Vår"
    },
    {
        "id": "yellow_anemone",
        "type": "Vårblommor",
        "nameEn": "Yellow Wood Anemone",
        "nameSv": "Gulsippa",
        "scientific": "Anemone ranunculoides",
        "rarity": 2,
        "funFact": "Gulsippan är mer sällsynt än vitsippan och växer på kalkrik mark i södra Sverige.",
        "seasonDistribution": "Södra Sverige",
        "height": 15,
        "color": "Gul",
        "bestTime": "Vår"
    },
    {
        "id": "hepatica",
        "type": "Vårblommor",
        "nameEn": "Hepatica",
        "nameSv": "Blåsippa",
        "scientific": "Hepatica nobilis",
        "rarity": 1,
        "funFact": "Blåsippan blommar redan i mars–april och kan vara blå, rosa eller vit. Sveriges nationalblomma sedan 1983.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 10,
        "color": "Blå/Lila",
        "bestTime": "Tidig vår"
    },
    {
        "id": "cowslip",
        "type": "Ängsblommor",
        "nameEn": "Cowslip",
        "nameSv": "Gullviva",
        "scientific": "Primula veris",
        "rarity": 2,
        "funFact": "Gullvivan är en symbol för den svenska vårängen och används som lager till örtte.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 25,
        "color": "Gul",
        "bestTime": "Vår"
    },
    {
        "id": "oxeye_daisy",
        "type": "Ängsblommor",
        "nameEn": "Oxeye Daisy",
        "nameSv": "Prästkrage",
        "scientific": "Leucanthemum vulgare",
        "rarity": 1,
        "funFact": "Prästkragen plockas flitigt till midsommarkransar och är en av de vanligaste ängsblommorna.",
        "seasonDistribution": "Hela landet",
        "height": 60,
        "color": "Vit/Gul",
        "bestTime": "Sommar"
    },
    {
        "id": "cornflower",
        "type": "Ängsblommor",
        "nameEn": "Cornflower",
        "nameSv": "Blåklint",
        "scientific": "Centaurea cyanus",
        "rarity": 2,
        "funFact": "Blåklinten är ett gammalt åkerogräs som minskat markant pga kemisk bekämpning men ger kraftig blå blomma.",
        "seasonDistribution": "Hela landet",
        "height": 50,
        "color": "Blå",
        "bestTime": "Sommar"
    },
    {
        "id": "common_poppy",
        "type": "Ängsblommor",
        "nameEn": "Common Poppy",
        "nameSv": "Kornvallmo",
        "scientific": "Papaver rhoeas",
        "rarity": 2,
        "funFact": "Kornvallmon blommar i lysande rött och var förr ett vanligt åkerogräs. Blomman håller bara en dag.",
        "seasonDistribution": "Södra Sverige",
        "height": 40,
        "color": "Röd",
        "bestTime": "Sommar"
    },
    {
        "id": "common_dandelion",
        "type": "Ängsblommor",
        "nameEn": "Dandelion",
        "nameSv": "Maskros",
        "scientific": "Taraxacum officinale",
        "rarity": 1,
        "funFact": "Maskrosen producerar frön utan befruktning (apomixis) och är en av de viktigaste pollenresurserna för bin tidigt på våren.",
        "seasonDistribution": "Hela landet",
        "height": 20,
        "color": "Gul",
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "red_clover",
        "type": "Ängsblommor",
        "nameEn": "Red Clover",
        "nameSv": "Rödklöver",
        "scientific": "Trifolium pratense",
        "rarity": 1,
        "funFact": "Rödklövern är en viktig honungsväxt och symbolvård i det svenska jordbruket för att berika marken med kväve.",
        "seasonDistribution": "Hela landet",
        "height": 40,
        "color": "Lila/Rosa",
        "bestTime": "Sommar"
    },
    {
        "id": "meadow_buttercup",
        "type": "Ängsblommor",
        "nameEn": "Meadow Buttercup",
        "nameSv": "Smörblomma",
        "scientific": "Ranunculus acris",
        "rarity": 1,
        "funFact": "Smörblomman används i det gamla leketr att hålla under hakan – om det är gult syns att man gillar smör.",
        "seasonDistribution": "Hela landet",
        "height": 60,
        "color": "Gul",
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "wild_strawberry",
        "type": "Skogsblommor",
        "nameEn": "Wild Strawberry",
        "nameSv": "Smultron",
        "scientific": "Fragaria vesca",
        "rarity": 1,
        "funFact": "Smultronet är ett av de godaste viltväxande frukterna i Sverige och växer i gläntor och vägkanter.",
        "seasonDistribution": "Hela landet",
        "height": 15,
        "color": "Vit",
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "herb_robert",
        "type": "Skogsblommor",
        "nameEn": "Herb-Robert",
        "nameSv": "Stinknäva",
        "scientific": "Geranium robertianum",
        "rarity": 1,
        "funFact": "Stinknävan doftar starkt när man rör den – trots luktens rykte är den en charmig liten rosa blomma.",
        "seasonDistribution": "Hela landet",
        "height": 30,
        "color": "Rosa",
        "bestTime": "Sommar"
    },
    {
        "id": "lily_of_the_valley",
        "type": "Skogsblommor",
        "nameEn": "Lily of the Valley",
        "nameSv": "Liljekonvalje",
        "scientific": "Convallaria majalis",
        "rarity": 1,
        "funFact": "Liljekonvaljens doft är en av de mest ikoniska vårdofterna. OBS: Hela växten är giftig!",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 20,
        "color": "Vit",
        "bestTime": "Vår"
    },
    {
        "id": "wild_orchid_spotted",
        "type": "Orkidéer",
        "nameEn": "Common Spotted Orchid",
        "nameSv": "Fläckig nyckelblomster",
        "scientific": "Dactylorhiza maculata",
        "rarity": 2,
        "funFact": "En av Sveriges vanligaste orkidéer – trots att den är relativt vanlig är alla svenska orkidéer fredade.",
        "seasonDistribution": "Hela landet (ängar)",
        "height": 30,
        "color": "Rosa/Lila",
        "bestTime": "Sommar"
    },
    {
        "id": "early_purple_orchid",
        "type": "Orkidéer",
        "nameEn": "Early Purple Orchid",
        "nameSv": "Adam och Eva",
        "scientific": "Orchis mascula",
        "rarity": 3,
        "funFact": "Adam och Eva blommar tidigt på våren och har ett fläckigt bladverk. Fridlyst i Sverige.",
        "seasonDistribution": "Södra Sverige",
        "height": 30,
        "color": "Lila",
        "bestTime": "Vår"
    },
    {
        "id": "lady_slipper",
        "type": "Orkidéer",
        "nameEn": "Lady's Slipper Orchid",
        "nameSv": "Guckusko",
        "scientific": "Cypripedium calceolus",
        "rarity": 5,
        "funFact": "Guckuskon är Sveriges vackraste orkidé och en av de sällsyntaste blommorna. Fridlyst och EU-skyddad.",
        "seasonDistribution": "Norra och mellersta Sverige (sparsam)",
        "height": 40,
        "color": "Gul/Rödbrun",
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "common_heather",
        "type": "Hedblommor",
        "nameEn": "Common Heather",
        "nameSv": "Ljung",
        "scientific": "Calluna vulgaris",
        "rarity": 1,
        "funFact": "Ljungens lila hav på svenska hedar och myrar ger en av höstens mest stämningsfulla naturupplevelser.",
        "seasonDistribution": "Hela landet",
        "height": 50,
        "color": "Lila/Rosa",
        "bestTime": "Sommar/Höst"
    },
    {
        "id": "fireweed",
        "type": "Ängsblommor",
        "nameEn": "Fireweed / Rosebay Willowherb",
        "nameSv": "Mjölkört",
        "scientific": "Chamerion angustifolium",
        "rarity": 1,
        "funFact": "Mjölkörten kallas 'brandens blomma' och är ofta det första som växer på avverkade eller brända ytor.",
        "seasonDistribution": "Hela landet",
        "height": 120,
        "color": "Lila/Rosa",
        "bestTime": "Sommar"
    },
    {
        "id": "wild_violet",
        "type": "Skogsblommor",
        "nameEn": "Sweet Violet",
        "nameSv": "Luktviol",
        "scientific": "Viola odorata",
        "rarity": 2,
        "funFact": "Luktvioalens intensiva doft har använts i parfymer i hundrtals år. Blommar redan i mars.",
        "seasonDistribution": "Södra Sverige",
        "height": 12,
        "color": "Lila",
        "bestTime": "Tidig vår"
    },
    {
        "id": "common_speedwell",
        "type": "Ängsblommor",
        "nameEn": "Germander Speedwell",
        "nameSv": "Stor ärenpris",
        "scientific": "Veronica chamaedrys",
        "rarity": 1,
        "funFact": "Den lilla blå blomman kallas ibland 'kattögon' och tappar sina kronblad snabbt när den plockas.",
        "seasonDistribution": "Hela landet",
        "height": 20,
        "color": "Blå",
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "water_lily",
        "type": "Vattenblommor",
        "nameEn": "White Water Lily",
        "nameSv": "Vit näckros",
        "scientific": "Nymphaea alba",
        "rarity": 1,
        "funFact": "Näckrosen är ett nationellt kärt inslag i sjölandskapet. Blommorna öppnar vid soluppgång och stängs vid solnedgång.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 10, // above water
        "color": "Vit",
        "bestTime": "Sommar"
    },
    {
        "id": "yellow_water_lily",
        "type": "Vattenblommor",
        "nameEn": "Yellow Water Lily",
        "nameSv": "Gul näckros",
        "scientific": "Nuphar lutea",
        "rarity": 1,
        "funFact": "Den gula näckrosen luktar svagt av alkohol och lockar flugorna som pollinerar den på ett unikt vis.",
        "seasonDistribution": "Hela landet",
        "height": 10,
        "color": "Gul",
        "bestTime": "Sommar"
    },
    {
        "id": "marsh_marigold",
        "type": "Vattenblommor",
        "nameEn": "Marsh Marigold",
        "nameSv": "Kabbleka",
        "scientific": "Caltha palustris",
        "rarity": 1,
        "funFact": "Kabblelkan lyser klarasguld vid bäckar och kärr tidigt på våren och är en njutning att hitta.",
        "seasonDistribution": "Hela landet",
        "height": 30,
        "color": "Gul",
        "bestTime": "Vår"
    },
    {
        "id": "wild_garlic",
        "type": "Skogsblommor",
        "nameEn": "Wild Garlic / Ramsons",
        "nameSv": "Ramslök",
        "scientific": "Allium ursinum",
        "rarity": 2,
        "funFact": "Ramslöken täcker hela skogsmarken med vitgröna mattor och kraftig vitlökslukt under april–maj.",
        "seasonDistribution": "Södra Sverige",
        "height": 40,
        "color": "Vit",
        "bestTime": "Vår"
    },
    {
        "id": "twinflower",
        "type": "Skogsblommor",
        "nameEn": "Twinflower",
        "nameSv": "Linnea",
        "scientific": "Linnaea borealis",
        "rarity": 2,
        "funFact": "Linnean är uppkallad efter Carl von Linné – botanikens fader – och var hans favoritblomma.",
        "seasonDistribution": "Norra och mellersta Sverige",
        "height": 10,
        "color": "Rosa",
        "bestTime": "Sommar"
    },
    {
        "id": "foxglove",
        "type": "Skogsblommor",
        "nameEn": "Foxglove",
        "nameSv": "Fingerborgsblomster",
        "scientific": "Digitalis purpurea",
        "rarity": 2,
        "funFact": "Fingerborgsblomstret är vacker men giftig. Dess ämne digitalis används dock som hjärtmedicin.",
        "seasonDistribution": "Södra och västra Sverige",
        "height": 120,
        "color": "Lila/Rosa",
        "bestTime": "Sommar"
    },
    {
        "id": "harebell",
        "type": "Ängsblommor",
        "nameEn": "Harebell",
        "nameSv": "Liten blåklocka",
        "scientific": "Campanula rotundifolia",
        "rarity": 1,
        "funFact": "Blåklockan ringlar sina klockformade blommor i vinden och är en vanlig syn i ängar och berg.",
        "seasonDistribution": "Hela landet",
        "height": 30,
        "color": "Blå/Lila",
        "bestTime": "Sommar"
    },
    {
        "id": "midsummer_flower",
        "type": "Ängsblommor",
        "nameEn": "Meadow Clary",
        "nameSv": "Åkervädd",
        "scientific": "Scabiosa arvensis",
        "rarity": 2,
        "funFact": "Åkervädden plockas till midsommarkransar och är en av de viktigaste fjärilsblommorna i Sverige.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 60,
        "color": "Lila/Blå",
        "bestTime": "Sommar"
    },
    {
        "id": "wild_pansy",
        "type": "Ängsblommor",
        "nameEn": "Wild Pansy",
        "nameSv": "Styvmorsviol",
        "scientific": "Viola tricolor",
        "rarity": 1,
        "funFact": "Styvmorsviolen har blommor i tre färger (lila, gult och vitt) och är urancestorn till odlade pensèer.",
        "seasonDistribution": "Hela landet",
        "height": 15,
        "color": "Lila/Gul/Vit",
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "fly_orchid",
        "type": "Orkidéer",
        "nameEn": "Fly Orchid",
        "nameSv": "Flugblomster",
        "scientific": "Ophrys insectifera",
        "rarity": 4,
        "funFact": "Flugblomstrets blomma ser ut som en stekelhona för att lura stekelhanar att pollinera den.",
        "seasonDistribution": "Gotland, Öland m.fl.",
        "height": 30,
        "color": "Mörkbrun/Lila",
        "bestTime": "Sommar"
    }
];
