
// List of trees in Sweden
// Categories: Lövträd, Barrträd, Ädla lövträd

window.swedishTrees = [
    {
        "id": "silver_birch",
        "type": "Lövträd",
        "nameEn": "Silver Birch",
        "nameSv": "Vårtbjörk",
        "scientific": "Betula pendula",
        "rarity": 1,
        "funFact": "Vårtbjörken känns igen på sina hängande grenar och vita stam med svarta sprickor.",
        "seasonDistribution": "Hela landet",
        "height": 25,
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "downy_birch",
        "type": "Lövträd",
        "nameEn": "Downy Birch",
        "nameSv": "Glasbjörk",
        "scientific": "Betula pubescens",
        "rarity": 1,
        "funFact": "Glasbjöken trivs på fuktigare mark än vårtbjörken och har slätare bark.",
        "seasonDistribution": "Hela landet (särskilt i norr)",
        "height": 20,
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "scots_pine",
        "type": "Barrträd",
        "nameEn": "Scots Pine",
        "nameSv": "Tall",
        "scientific": "Pinus sylvestris",
        "rarity": 1,
        "funFact": "Tallen är, tillsammans med granen, Sveriges vanligaste träd.",
        "seasonDistribution": "Hela landet",
        "height": 30,
        "bestTime": "Året runt"
    },
    {
        "id": "norway_spruce",
        "type": "Barrträd",
        "nameEn": "Norway Spruce",
        "nameSv": "Gran",
        "scientific": "Picea abies",
        "rarity": 1,
        "funFact": "Granen är det träd som ger mest virke i Sverige.",
        "seasonDistribution": "Hela landet (utom kalfjället)",
        "height": 35,
        "bestTime": "Året runt"
    },
    {
        "id": "oak",
        "type": "Ädla lövträd",
        "nameEn": "English Oak",
        "nameSv": "Ek",
        "scientific": "Quercus robur",
        "rarity": 2,
        "funFact": "Eken kan bli över 1000 år gammal och ger livsrum åt tusentals insekter.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 25,
        "bestTime": "Vår/Sommar/Höst"
    },
    {
        "id": "beech",
        "type": "Ädla lövträd",
        "nameEn": "European Beech",
        "nameSv": "Bok",
        "scientific": "Fagus sylvatica",
        "rarity": 2,
        "funFact": "Bokskogar är kända för att vara mörka och sakna undervegetation pga det täta lövverket.",
        "seasonDistribution": "Södra Sverige",
        "height": 30,
        "bestTime": "Vår/Sommar/Höst"
    },
    {
        "id": "european_ash",
        "type": "Ädla lövträd",
        "nameEn": "European Ash",
        "nameSv": "Ask",
        "scientific": "Fraxinus excelsior",
        "rarity": 3,
        "funFact": "Asken slår ut sina löv sent och fäller dem tidigt.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 30,
        "bestTime": "Sommar"
    },
    {
        "id": "wych_elm",
        "type": "Ädla lövträd",
        "nameEn": "Wych Elm",
        "nameSv": "Skogsalm",
        "scientific": "Ulmus glabra",
        "rarity": 3,
        "funFact": "Almens blad är sträva och asymmetriska vid basen.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 30,
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "norway_maple",
        "type": "Ädla lövträd",
        "nameEn": "Norway Maple",
        "nameSv": "Lönn",
        "scientific": "Acer platanoides",
        "rarity": 2,
        "funFact": "Lönnens löv får fantastiska röda och gula färger på hösten.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 25,
        "bestTime": "Höst"
    },
    {
        "id": "small_leaved_lime",
        "type": "Ädla lövträd",
        "nameEn": "Small-leaved Lime",
        "nameSv": "Lind",
        "scientific": "Tilia cordata",
        "rarity": 3,
        "funFact": "Linden kallas ofta för 'kyrkogårdsträd' och dess blommor doftar sött.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 25,
        "bestTime": "Sommar"
    },
    {
        "id": "aspen",
        "type": "Lövträd",
        "nameEn": "Aspen",
        "nameSv": "Asp",
        "scientific": "Populus tremula",
        "rarity": 1,
        "funFact": "Aspens blad darrar vid minsta vindpust ('darra som ett asplöv').",
        "seasonDistribution": "Hela landet",
        "height": 20,
        "bestTime": "Vår/Sommar/Höst"
    },
    {
        "id": "rowan",
        "type": "Lövträd",
        "nameEn": "Rowan",
        "nameSv": "Rönn",
        "scientific": "Sorbus aucuparia",
        "rarity": 1,
        "funFact": "Rönnen får röda bär på hösten som är viktig föda för fåglar.",
        "seasonDistribution": "Hela landet",
        "height": 15,
        "bestTime": "Höst"
    },
    {
        "id": "juniper",
        "type": "Barrträd",
        "nameEn": "Juniper",
        "nameSv": "En",
        "scientific": "Juniperus communis",
        "rarity": 1,
        "funFact": "Enen är en buske eller litet träd vars bär används som krydda.",
        "seasonDistribution": "Hela landet",
        "height": 6,
        "bestTime": "Året runt"
    },
    {
        "id": "goat_willow",
        "type": "Lövträd",
        "nameEn": "Goat Willow",
        "nameSv": "Sälg",
        "scientific": "Salix caprea",
        "rarity": 1,
        "funFact": "Sälgen blommar tidigt på våren och är ett viktig pollenkälla för bin och humlor.",
        "seasonDistribution": "Hela landet",
        "height": 10,
        "bestTime": "Vår"
    },
    {
        "id": "bird_cherry",
        "type": "Lövträd",
        "nameEn": "Bird Cherry",
        "nameSv": "Hägg",
        "scientific": "Prunus padus",
        "rarity": 1,
        "funFact": "Häggens vita blomklasar doftar intensivt och markerar vårens ankomst i hela landet.",
        "seasonDistribution": "Hela landet",
        "height": 12,
        "bestTime": "Vår"
    },
    {
        "id": "hawthorn",
        "type": "Buskar",
        "nameEn": "Common Hawthorn",
        "nameSv": "Hagtorn",
        "scientific": "Crataegus monogyna",
        "rarity": 1,
        "funFact": "Hagtornet kallas 'skogens apotekare' och används sedan urminnes tider som hjärtmedicin.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 6,
        "bestTime": "Vår/Höst"
    },
    {
        "id": "alder",
        "type": "Lövträd",
        "nameEn": "Grey Alder",
        "nameSv": "Klibbal",
        "scientific": "Alnus glutinosa",
        "rarity": 1,
        "funFact": "Klibbalens rötter binder kväve från luften och förbättrar marken där den växer.",
        "seasonDistribution": "Hela landet",
        "height": 20,
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "black_alder",
        "type": "Lövträd",
        "nameEn": "Black Alder",
        "nameSv": "Svartal",
        "scientific": "Alnus incana",
        "rarity": 1,
        "funFact": "Svartalens ved är vattentålig och användes historiskt till vattenpålar och träskor.",
        "seasonDistribution": "Hela landet",
        "height": 15,
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "whitebeam",
        "type": "Lövträd",
        "nameEn": "Swedish Whitebeam",
        "nameSv": "Oxel",
        "scientific": "Sorbus intermedia",
        "rarity": 2,
        "funFact": "Oxeln är endem för den skandinaviska halvön och nästan bara förekommande i Sverige och Norge.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 15,
        "bestTime": "Vår/Höst"
    },
    {
        "id": "crab_apple",
        "type": "Lövträd",
        "nameEn": "Crab Apple",
        "nameSv": "Vildapel",
        "scientific": "Malus sylvestris",
        "rarity": 3,
        "funFact": "Vildapeln är urancestorn till alla odlade äpplen och är nu sällsynt i Sverige.",
        "seasonDistribution": "Södra Sverige",
        "height": 8,
        "bestTime": "Vår/Höst"
    },
    {
        "id": "wild_cherry",
        "type": "Lövträd",
        "nameEn": "Wild Cherry",
        "nameSv": "Fågelbär",
        "scientific": "Prunus avium",
        "rarity": 2,
        "funFact": "Fågelbäret är urancestorn till körsbär och får en magnifik blomning i maj.",
        "seasonDistribution": "Södra och mellersta Sverige",
        "height": 20,
        "bestTime": "Vår/Höst"
    },
    {
        "id": "wych_elm2",
        "type": "Ädla lövträd",
        "nameEn": "Field Elm",
        "nameSv": "Alm",
        "scientific": "Ulmus minor",
        "rarity": 3,
        "funFact": "Almen har drabbats hårt av almsjukan men gamla exemplar kan fortfarande ses i sydsvenska byar.",
        "seasonDistribution": "Södra Sverige",
        "height": 25,
        "bestTime": "Vår/Sommar"
    },
    {
        "id": "hornbeam",
        "type": "Ädla lövträd",
        "nameEn": "European Hornbeam",
        "nameSv": "Avenbok",
        "scientific": "Carpinus betulus",
        "rarity": 3,
        "funFact": "Avenboken har en karakteristisk muskelstam och det hårdaste virket av alla europeiska lövträd.",
        "seasonDistribution": "Södra Sverige",
        "height": 20,
        "bestTime": "Vår/Höst"
    },
    {
        "id": "yew",
        "type": "Barrträd",
        "nameEn": "Common Yew",
        "nameSv": "Idegran",
        "scientific": "Taxus baccata",
        "rarity": 3,
        "funFact": "Idegranen är ett av Europas äldsta träd och kan bli över 5000 år. Bären är giftiga, men köttet är ej.",
        "seasonDistribution": "Södra Sverige",
        "height": 15,
        "bestTime": "Året runt"
    },
    {
        "id": "field_maple",
        "type": "Ädla lövträd",
        "nameEn": "Field Maple",
        "nameSv": "Naverlönn",
        "scientific": "Acer campestre",
        "rarity": 3,
        "funFact": "Naverlönnen är den enda till Sverige inhemska lönnarten och ger en vacker gulröd höstfärg.",
        "seasonDistribution": "Södra Sverige",
        "height": 15,
        "bestTime": "Höst"
    }
];
